[package]
name = "wstf_algorithms"
version = "0.1.0"
authors = ["alxshelepenok <alxshelepenok@gmail.com>"]
repository = "https://github.com/wtrscape/wstf"
description = "Implementation of algorithms and data structures"
edition = "2018"

[dependencies]
byteorder = "1.3.2"
chrono = "0.4.9"
indexmap = "1.9.1"
libc = "0.2.62"
wstf_protocol = { path = "../wstf_protocol", version = "0.1.0" }
wstf_update = { path = "../wstf_update", version = "0.1.0" }
wstf_utils = { path = "../wstf_utils", version = "0.1.0" }
