[package]
name = "wstf_protocol"
version = "0.1.0"
authors = ["alxshelepenok <alxshelepenok@gmail.com>"]
repository = "https://github.com/wtrscape/wstf"
description = "Implementation of WSTF Protocol"
edition = "2018"

[dependencies]
bitflags = "1.3.2"
byteorder = "1.4.3"
serde = "1.0.152"
serde_derive = "1.0.151"
serde_json = "1.0.91"
wstf_utils = { path = "../wstf_utils", version = "0.1.0" }
wstf_update = { path = "../wstf_update", version = "0.1.0" }

[dev-dependencies]
serial_test = "0.10.0"
