[package]
name = "wstf_update"
version = "0.1.0"
authors = ["alxshelepenok <alxshelepenok@gmail.com>"]
repository = "https://github.com/wtrscape/wstf"
description = "Implementation of WSTF Update"
edition = "2018"

[dependencies]
bitflags = "1.3.2"
byteorder = "1.4.3"
serde = "1.0.148"
serde_derive = "1.0.147"
serde_json = "1.0.89"
