[package]
name = "wstf_parser"
version = "0.1.0"
authors = ["alxshelepenok <alxshelepenok@gmail.com>"]
repository = "https://github.com/wtrscape/wstf"
description = "Implementation of WSTF parser"
edition = "2018"

[dependencies]
csv = "1.1.6"
serde = "1.0.147"
libc = "0.2.137"
serde_derive = "1.0.147"
serde_json = "1.0.40"
wstf_protocol = { path = "../wstf_protocol", version = "0.1.0" }
wstf_update = { path = "../wstf_update", version = "0.1.0" }
wstf_utils = { path = "../wstf_utils", version = "0.1.0" }

[dependencies.uuid]
features = ["serde", "v4"]
version = "0.8.2"
