[package]
name = "wstf_database"
version = "0.1.0"
authors = ["alxshelepenok <alxshelepenok@gmail.com>"]
repository = "https://github.com/wtrscape/wstf"
description = "Implementation of WSTF Database"
edition = "2018"

[dependencies]
byteorder = "1.4.3"
wstf_protocol = { path = "../wstf_protocol", version = "0.1.0" }
wstf_update = { path = "../wstf_update", version = "0.1.0" }
log = "0.4.17"
